### ISSUE TITLE
Not Support Unicode

### ISSUE THREAD

**Issue by ryrun168** [tuhrig/Flying_Saucer_PDF_Generation#1]
Hi Team, 

I have generate it with unicode , i already imported font unicode, but it's unknown.

Could you help ?

**Comment by tuhrig** [comment]
Hey @ryrun168 ! You can achieve this with some CSS.

1. Download the font you want to use and put it in the root folder of the project. Just as I did with the Code39.ttf.
2. Edit the style.css in order to use the font:

```
@font-face {
    font-family: myFirstFont;
    src: url(INSULA__.ttf);
    -fs-pdf-font-embed: embed;
    -fs-pdf-font-encoding: Identity-H;
}

body {
    font-family: myFirstFont;
    font-size: 12px;
}
```

That's all you need. I've tested it and I can see the unicode characters as expected in PDF.
